### ISSUE TITLE
Backend GHA job black fails on unittest

### ISSUE THREAD

**Issue by Fosten** [collective/cookiecutter-plone-starter#60]
Not sure what is causing this.
My last successful backend build was Jan 30.
Wondering if something changed in the Feb 1-2 commits?

============================
Starting plone-code-analysis
============================

Running check: black
====================
--- ./backend/src/plone_mountain_site/src/plone_mountain_site/tests/test_setup.py	2023-02-13 21:23:30.281300 +0000
+++ ./backend/src/plone_mountain_site/src/plone_mountain_site/tests/test_setup.py	2023-02-13 21:23:30.[9](https://github.com/Fosten/plone-mountain-site/actions/runs/4167961594/jobs/7214178656#step:4:10)53706 +0000
@@ -1,[10](https://github.com/Fosten/plone-mountain-site/actions/runs/4167961594/jobs/7214178656#step:4:11) +1,[12](https://github.com/Fosten/plone-mountain-site/actions/runs/4167961594/jobs/7214178656#step:4:13) @@
 """Setup tests for this package."""
 from plone import api
 from plone.app.testing import setRoles
 from plone.app.testing import TEST_USER_ID
-from plone_mountain_site.testing import PLONE_MOUNTAIN_SITE_INTEGRATION_TESTING  # noqa: E501
+from plone_mountain_site.testing import (
+    PLONE_MOUNTAIN_SITE_INTEGRATION_TESTING,
+)  # noqa: E501
 from Products.CMFPlone.utils import get_installer
 
 import unittest
 
 

would reformat ./backend/src/plone_mountain_site/src/plone_mountain_site/tests/test_setup.py

Oh no! 💥 💔 💥
1 file would be reformatted, [20](https://github.com/Fosten/plone-mountain-site/actions/runs/4167961594/jobs/7214178656#step:4:21) files would be left unchanged.

=======
Results
=======
There were errors

**Comment by stevepiercy** [comment]
Most likely you need to upgrade your version of Black as there was a new release on 2023-01-31.

https://pypi.org/project/black/#history

**Comment by Fosten** [comment]
@stevepiercy 
https://github.com/collective/cookiecutter-plone-starter/blob/f339e5c6a5dc967c4c2f1d5abadc3b3cc9a09651/pyproject.toml#L1-L3

I tried changing py38 to py311 but there was no change, build still failed.

But, good news!  FIXED.  The problem was here:
 https://github.com/collective/cookiecutter-plone-starter/blob/43d25ccd68e7b47bb35c344c6a96cee5485c0f81/%7B%7B%20cookiecutter.project_slug%20%7D%7D/backend/src/%7B%7B%20cookiecutter.python_package_name%20%7D%7D/src/%7B%7B%20cookiecutter.python_package_name%20%7D%7D/tests/test_setup.py#L5
Removed the # noqa: E501 comment and it worked

**Comment by stevepiercy** [comment]
That does not "fix" the issue, but instead requires it to be checked by other linters, which may bring about other issues.

Black wants to reformat your import statement because its line length exceeds 88 characters at 92 characters. This might have nothing to do with the recent release of the latest Black, but it is still possible.

Did you previously use a shorter name for your package than `PLONE_MOUNTAIN_SITE`, or has it always been that?

Can you use a shorter name for your constant `PLONE_MOUNTAIN_SITE_INTEGRATION_TESTING`?

To actually fix this in the cookiecutter template, we might consider shortening the length of the suffix `_INTEGRATION_TESTING`.

https://github.com/collective/cookiecutter-plone-starter/blob/main/%7B%7B%20cookiecutter.project_slug%20%7D%7D/backend/src/%7B%7B%20cookiecutter.python_package_name%20%7D%7D/src/%7B%7B%20cookiecutter.python_package_name%20%7D%7D/tests/test_setup.py#L5

Alternatively we could conditionally format the line according to Black.

```diff
-from plone_mountain_site.testing import PLONE_MOUNTAIN_SITE_INTEGRATION_TESTING # noqa: E501
+from plone_mountain_site.testing import (
  PLONE_MOUNTAIN_SITE_INTEGRATION_TESTING,
+) # noqa: E501
```
